### ISSUE TITLE
MDS count incorrect?

### ISSUE THREAD

**Issue by djgalloway** [ceph/cephmetrics#107]
This may be intentional but the Sepia cluster has 3 MDSes.  Of course two are standbys but cephmetrics only shows 1.

```
  services:
    mon: 3 daemons, quorum mira021,mira049,mira060
    mgr: mira049(active), standbys: mira021, mira060
    mds: 1/1/1 up {0=mira049=up:active}, 2 up:standby
```
